export const techSkillsList = [
    // Programming Languages
    "JavaScript",
    "Python",
    "Java",
    "C#",
    "C++",
    "Ruby",
    "Swift",
    "Kotlin",
    "TypeScript",
    "PHP",
    "Go",
    "Rust",
    "Dart",
    "Scala",
    "Perl",
    "R",
    "Objective-C",
    "SQL",
    "Shell Scripting",
    "Bash",
    "PowerShell",
    "HTML",
    "CSS",
    "XML",
    "JSON",
    "YAML",
    "Markdown",
    "Assembly Language",
    "MATLAB",
    "VHDL",
    "Verilog",
    "COBOL",
    "Fortran",
    "Ada",
    "Lisp",
    "Scheme",
    "Prolog",
    "Haskell",
    "Erlang",
    "Clojure",
    "Elixir",
    "F#",


    // Frontend Development
    "HTML5",
    "CSS3",
    "React.js",
    "Angular",
    "Vue.js",
    "Bootstrap",
    "Sass",
    "Less",
    "jQuery",
    "Webpack",
    "Babel",
    "Redux",
    "GraphQL",
    "Next.js",
    "Gatsby",
    "Nuxt.js",
    "Tailwind CSS",
    "Material-UI",
    "Ant Design",
    "Chakra UI",
    "Styled Components",
    "Emotion",
    "Framer Motion",
    "Three.js",
    "D3.js",
    "Chart.js",
    "recharts",
    "Highcharts",
    "Mapbox",
    "Leaflet",
    "Google Maps API",
    "Apollo Client",
    "Axios",
    "Fetch API",
    "REST APIs",
    "WebSocket",
    "Service Workers",
    "Progressive Web Apps (PWAs)",
    "Responsive Web Design",
    "Cross-browser Compatibility",
    "Web Performance Optimization",

    // Backend Development
    "Node.js",
    "Express.js",
    "Django",
    "Flask",
    "Spring Boot",
    "ASP.NET",
    "Ruby on Rails",
    "Laravel",
    "Flask",
    "Symfony",
    "GraphQL",
    "RESTful APIs",
    "Microservices",

    // Databases
    "MySQL",
    "PostgreSQL",
    "MongoDB",
    "SQLite",
    "Microsoft SQL Server",
    "Oracle",
    "Redis",
    "Firebase",
    "Couchbase",
    "Cassandra",
    "DynamoDB",

    // DevOps/Tools
    "Docker",
    "Kubernetes",
    "Jenkins",
    "Travis CI",
    "GitLab CI/CD",
    "GitHub Actions",
    "AWS",
    "Google Cloud Platform (GCP)",
    "Microsoft Azure",
    "Terraform",
    "Ansible",
    "Puppet",
    "Chef",
    "Nginx",
    "Apache HTTP Server",

    // Mobile Development
    "React Native",
    "Flutter",
    "Swift (iOS)",
    "Kotlin (Android)",
    "Xamarin",
    "Ionic",
    "PhoneGap/Cordova",
    "NativeScript",
    "Java (Android)",
    "Objective-C (iOS)",
    "Firebase Cloud Messaging (FCM)",
    "Push Notifications",
    "APNs",
    "Google Cloud Messaging (GCM)",
    "Maps SDK",
    "Location-based Services",
    "Koitlin",
    "SwiftUI",
    "Jetpack Compose",
    "ARCore",

    // Testing
    "Jest",
    "Mocha",
    "Jasmine",
    "Selenium",
    "Cypress",
    "Puppeteer",
    "JUnit",
    "TestNG",
    "NUnit",
    "Mockito",
    "PowerMock",
    "Robot Framework",
    "Postman",
    "Swagger",

    // Other Technologies
    "Blockchain",
    "Machine Learning",
    "Artificial Intelligence",
    "Data Science",
    "Big Data",
    "Natural Language Processing (NLP)",
    "Computer Vision",
    "Internet of Things (IoT)",
    "Augmented Reality (AR) / Virtual Reality (VR)",
    "Cybersecurity",
    "Web Accessibility",
    "Progressive Web Apps (PWAs)",

    // Project Management
    "Agile Methodologies",
    "Scrum",
    "Kanban",
    "Lean",
    "Waterfall",
    "Project Planning",
    "Risk Management",
    "Budgeting",
    "Stakeholder Management",
    "Resource Allocation",
    "Team Leadership",
    "Communication Skills",
    "Problem-solving",
    "Decision-making",

    // Scrum Master Skills
    "Facilitation",
    "Coaching",
    "Servant Leadership",
    "Conflict Resolution",
    "Empathy",
    "Time Management",
    "Change Management",
    "Continuous Improvement",
    "Metrics and Reporting",
    "Team Building",
    "Collaboration",
    "Adaptability",
    "Negotiation",
    "Problem-solving",
    "Decision-making",
    "Technical Skills",
    "Agile Principles",
    "Scrum Framework",
    "Kanban Methodology",
    "Lean Principles",
    "SAFe (Scaled Agile Framework)",
    "Jira",
    "Confluence",
    "Trello",
    "Azure DevOps",
    "VersionOne",
    "Rally",
    "Slack",

    //Managerial skills
    "Leadership",
    "Strategic Planning",
    "Performance Management",
    "Team Building",
    "Decision Making",
    "Problem Solving",
    "Conflict Resolution",
    "Change Management",
    "Communication Skills",
    "Interpersonal Skills",
    "Time Management",
    "Delegation",
    "Motivation",
    "Coaching",
    "Mentoring",
    "Training",
    "Feedback",
    "Empathy",
    "Creativity",
    "Innovation",
    "Adaptability",
    "Flexibility",
    "Negotiation",


    // Additional skills from job descriptions

    // Senior Devops Engineer
    "Powershell",
    "CICD Pipeline Management",
    "Load Balancing",
    "Azure App Gateway",
    "Azure Application Insights",
    "Key Vault (KV)",
    "Troubleshooting",

    // CMDB Service Now Delivery
    "IT Asset Management (ITAM)",
    "SCCM (System Center Configuration Manager)",
    "Prioritization",
    "Delegation",
    "Leadership Development",

    // Data Engineer with Python
    "Azure Data Factory (ADF)",
    "Azure Synapse Analytics",
    "Azure Function",
    "Azure Storage (Blob Storage)",
    "GCP Vertex AI",
    "Google BigQuery",
    "Google Cloud Storage",
    "AWS Redshift",
    "AWS SageMaker",
    "AWS S3",
    "Data Modeling",
    "Cloud Analytics",
    "Data Warehousing",
    "ETL (Extract, Transform, Load)",
    "Data Pipelines",
    "Data Lakes",
    "Data Governance",
    "Data Quality",
    // Programming Languages
    "SAS",
    "Forth",
    "Pascal",
    "Groovy",
    "OCaml",
    "ABAP",
    "PL/SQL",
    "Awk",
    "Sed",
    "Julia",
    "ColdFusion",
    "Smalltalk",

    // Frontend Development
    "Svelte",
    "Alpine.js",
    "Backbone.js",
    "Mithril",
    "Polymer",
    "LitElement",
    "Stencil",
    "Parcel",
    "Grunt",
    "Gulp",
    "Rollup",
    "Browserify",
    "Stencil",
    "Preact",

    // Backend Development
    "FastAPI",
    "NestJS",
    "Koa",
    "Hapi",
    "Meteor.js",
    "FeathersJS",
    "Sails.js",
    "LoopBack",
    "Phoenix",
    "Ktor",
    "Fiber (Go)",
    "Echo (Go)",
    "Gin (Go)",
    "Moleculer",
    "Actix",

    // Databases
    "Elasticsearch",
    "Neo4j",
    "ArangoDB",
    "InfluxDB",
    "TimescaleDB",
    "CouchDB",
    "OrientDB",
    "RethinkDB",
    "MariaDB",
    "CockroachDB",
    "TiDB",
    "ScyllaDB",
    "HBase",
    "Memcached",
    "VoltDB",

    // DevOps/Tools
    "Istio",
    "Consul",
    "Vault",
    "OpenShift",
    "Rancher",
    "Spinnaker",
    "Prometheus",
    "Grafana",
    "ELK Stack",
    "Splunk",
    "Logstash",
    "Fluentd",
    "Graylog",
    "Vagrant",
    "Packer",
    "Nexus",
    "SonarQube",
    "Artifactory",
    "CircleCI",
    "Buddy",
    "CodeShip",
    "Drone CI",
    "Octopus Deploy",
    "New Relic",
    "Datadog",
    "Sentry",
    "Zabbix",
    "Nagios",
    "Monit",
    "Checkmk",

    // Mobile Development
    "Kivy",
    "Apache Cordova",
    "Capacitor",
    "Appcelerator",
    "Onsen UI",
    "Corona SDK",
    "B4A (Basic4Android)",
    "Sencha Touch",
    "ReactiveX",
    "RxJava",
    "RxSwift",
    "RxKotlin",
    "MvvmCross",
    "Hilt",
    "Dagger",
    "Koin",

    // Testing
    "TestCafe",
    "Cucumber",
    "Chai",
    "Enzyme",
    "Ava",
    "Karma",
    "Protractor",
    "QUnit",
    "Jest Puppeteer",
    "CodeceptJS",
    "Nightwatch.js",
    "Gauge",
    "Allure",
    "Appium",
    "Espresso",
    "XCUITest",
    "TestFlight",
    "BrowserStack",
    "Sauce Labs",
    "Locust",
    "JMeter",
    "Artillery",
    "LoadRunner",

    // Other Technologies
    "Quantum Computing",
    "Robotic Process Automation (RPA)",
    "Edge Computing",
    "Federated Learning",
    "Digital Twins",
    "DevSecOps",
    "Ethical Hacking",
    "Penetration Testing",
    "Data Privacy",
    "GDPR Compliance",
    "Zero Trust Architecture",
    "5G Networks",
    "Smart Contracts",
    "Serverless Computing",
    "Low-Code/No-Code Platforms",
    "Data Visualization",
    "Predictive Analytics",
    "Edge AI",

    // Project Management
    "Scrum Master Certification",
    "PMP Certification",
    "Prince2",
    "Six Sigma",
    "ITIL",
    "TOGAF",
    "MS Project",
    "Asana",
    "Monday.com",
    "Basecamp",
    "Wrike",
    "ClickUp",
    "Smartsheet",
    "Notion",

    // Scrum Master Skills
    "Agile Coaching",
    "Team Dynamics",
    "Sprint Planning",
    "Sprint Retrospective",
    "User Story Mapping",
    "Backlog Grooming",
    "Release Planning",
    "Value Stream Mapping",
    "Technical Debt Management",

    // Managerial Skills
    "Operational Excellence",
    "Process Improvement",
    "Organizational Development",
    "Stakeholder Engagement",
    "KPI Setting and Tracking",
    "Financial Acumen",
    "Corporate Governance",
    "Business Continuity Planning",
    "Succession Planning",
    "Performance Metrics",
    "Resource Optimization",
    "Cultural Competence",

    // Additional skills from job descriptions

    // Data Engineer with Python
    "Airflow",
    "Luigi",
    "dbt (data build tool)",
    "Presto",
    "Trino",
    "Snowflake",
    "Google Data Studio",
    "Data Virtualization",
    "Apache Superset",
    "Looker",
    "Tableau",
    "Power BI",
    "Domo",
    "QlikView",
    "Sisense",
    "Mode Analytics",
    "Sigma Computing",
    "DataOps",
    "Stream Processing",
    "Event Sourcing",
    "Change Data Capture (CDC)",
    "Schema Evolution",

    // Machine Learning/AI
    "TensorFlow",
    "PyTorch",
    "Keras",
    "Scikit-Learn",
    "Hugging Face",
    "OpenCV",
    "NLTK",
    "SpaCy",
    "Gensim",
    "LightGBM",
    "XGBoost",
    "CatBoost",
    "Apache Spark MLlib",
    "MLflow",
    "Kubeflow",
    "TPU (Tensor Processing Unit)",
    "BERT",
    "GPT",
    "DALL-E",
    "Reinforcement Learning",
    "GANs (Generative Adversarial Networks)",
    "Time Series Analysis",
    "Anomaly Detection",
    "Predictive Maintenance",
    "MLOps",
    // AI/ML Libraries and Frameworks
    "TensorFlow",
    "PyTorch",
    "Keras",
    "Scikit-Learn",
    "XGBoost",
    "LightGBM",
    "CatBoost",
    "FastAI",
    "Caffe",
    "MXNet",
    "Chainer",
    "CNTK",
    "Theano",
    "OpenCV",
    "NLTK",
    "SpaCy",
    "Gensim",
    "Hugging Face Transformers",
    "AllenNLP",
    "Stanford NLP",
    "TextBlob",
    "Fairseq",
    "Flair",
    "Pattern",
    "DeepPavlov",
    "BERT",
    "GPT-3",
    "GPT-4",
    "DALL-E",
    "VGGNet",
    "ResNet",
    "YOLO (You Only Look Once)",
    "MobileNet",
    "EfficientNet",
    "UNet",
    "GANs (Generative Adversarial Networks)",
    "DCGAN",
    "CycleGAN",
    "StyleGAN",
    "Pix2Pix",
    "OpenAI Gym",
    "Ray RLlib",
    "Stable Baselines3",
    "Dopamine",
    "Horovod",
    "ONNX (Open Neural Network Exchange)",
    "MLflow",
    "Kubeflow",
    "Apache Spark MLlib",
    "BigDL",
    "H2O.ai",
    "DVC (Data Version Control)",
    "Weights & Biases",
    "Neptune.ai",
    "Comet.ml",
    "ClearML",
    "TensorBoard",
    "TensorRT",
    "TFLite",
    "OpenVINO",

    // Natural Language Processing (NLP)
    "SpaCy",
    "Gensim",
    "NLTK",
    "Hugging Face Transformers",
    "AllenNLP",
    "Stanford NLP",
    "TextBlob",
    "Pattern",
    "FastText",
    "Flair",
    "CoreNLP",
    "Polyglot",
    "OpenNLP",
    "BERT",
    "RoBERTa",
    "GPT-2",
    "GPT-3",
    "T5",
    "XLNet",
    "ERNIE",
    "Albert",
    "DistilBERT",
    "ELMo",
    "Word2Vec",
    "GloVe",
    "doc2vec",
    "Sentence Transformers",
    "ParlAI",
    "Dialogflow",
    "Rasa",
    "ChatterBot",
    "BotPress",

    // Computer Vision
    "OpenCV",
    "TensorFlow Object Detection API",
    "Detectron2",
    "MMDetection",
    "DeepLab",
    "YOLO",
    "Mask R-CNN",
    "Faster R-CNN",
    "SSD (Single Shot MultiBox Detector)",
    "RetinaNet",
    "UNet",
    "EfficientDet",
    "DeepFace",
    "Dlib",
    "face_recognition",
    "OpenPose",
    "MediaPipe",
    "PyTorch3D",
    "VisPy",
    "Mayavi",
    "PCL (Point Cloud Library)",
    "PyTorch Geometric",
    "Gradio",
    "Streamlit",
    "Dash",
    "Bokeh",
    "Plotly",

    // Reinforcement Learning
    "OpenAI Gym",
    "Stable Baselines3",
    "Ray RLlib",
    "TensorForce",
    "Dopamine",
    "Coach",
    "Horizon",
    "Surreal",
    "TF-Agents",
    "ACME",
    "Tonic",

    // Data Science and Analysis
    "Pandas",
    "NumPy",
    "SciPy",
    "Dask",
    "Vaex",
    "Polars",
    "Modin",
    "Geopandas",
    "PyArrow",
    "H2O.ai",
    "Rapids.ai",
    "Holoviews",
    "Seaborn",
    "Matplotlib",
    "Altair",
    "ggplot",
    "Bokeh",
    "Plotly",
    "Dash",
    "Geopy",
    "Shapely",
    "Fiona",
    "Folium",
    "Statsmodels",

    // Audio Processing
    "Librosa",
    "PyDub",
    "Wave",
    "Soundfile",
    "SpeechRecognition",
    "Transformers",
    "Wav2Vec",
    "DeepSpeech",
    "PyAudio",
    "Resampy",
    "Madmom",
    "Torchaudio",

    // LangChain and Conversational AI
    "LangChain",
    "Rasa",
    "Dialogflow",
    "Microsoft Bot Framework",
    "Amazon Lex",
    "IBM Watson Assistant",
    "ChatterBot",
    "BotPress",
    "TARS",
    "Wit.ai",
    "Botkit",
    "Snips",
    "Teneo",
    "Clinc",

    // OpenAI and GPT-based tools
    "OpenAI API",
    "GPT-3",
    "GPT-4",
    "DALL-E",
    "Codex",
    "Whisper",
    "CLIP",
    "Jukebox",
    "Microscope",
    "OpenAI Baselines",
    "OpenAI Gym",
    "Spinning Up",
    "Safety Gym",
    "Deep Q-Learning",

    // Additional AI Tools and Technologies
    "AutoML",
    "H2O AutoML",
    "Google AutoML",
    "TPOT",
    "Auto-Keras",
    "MLBox",
    "Neuraxle",
    "DataRobot",
    "DeepMind",
    "AlphaFold",
    "DeepDream",
    "OpenAI Five",
    "AlphaZero",
    "MuZero",
    "DeepTraffic",
    "DeepDrive",
    "RoboFlow",
    "Supervised Learning",
    "Unsupervised Learning",
    "Semi-Supervised Learning",
    "Self-Supervised Learning",
    "Transfer Learning",
    "Meta-Learning",
    "Few-Shot Learning",
    "Zero-Shot Learning",
    "Federated Learning",
    "Graph Neural Networks",
    "Capsule Networks",
    "Neural Architecture Search (NAS)",
    "Evolutionary Algorithms",
    "Swarm Intelligence",
    "Bayesian Optimization",
    "Markov Decision Processes",
    "Hidden Markov Models",
    "Monte Carlo Methods",
    "Stochastic Processes",
    "Time Series Forecasting",
    "Anomaly Detection",
    "Predictive Maintenance",
    "Natural Language Generation (NLG)",
    "Automatic Speech Recognition (ASR)",
    "Text-to-Speech (TTS)",
    "Computer Vision",
    "Semantic Segmentation",
    "Instance Segmentation",
    "3D Object Detection",
    "Point Cloud Processing",
    "Augmented Reality (AR)",
    "Virtual Reality (VR)",
    "Reinforcement Learning",
    "Multi-Agent Systems",
    "Robotic Process Automation (RPA)",
    "Edge AI",
    "TinyML",
    "Explainable AI (XAI)",
    "AI Fairness",
    "AI Ethics",
    "AI Governance",
    "AI Policy",
    "AI Research",
    "AI for Healthcare",
    "AI for Finance",
    "AI for Autonomous Vehicles",
    "AI for Cybersecurity",
    "AI for Agriculture",
    "AI for Education",
    "AI for Social Good",

    // Leadership Roles
    "Chief Executive Officer (CEO)",
    "Chief Technology Officer (CTO)",
    "Chief Operating Officer (COO)",
    "Chief Information Officer (CIO)",
    "Chief Financial Officer (CFO)",
    "Chief Marketing Officer (CMO)",
    "Chief Product Officer (CPO)",
    "Chief Data Officer (CDO)",
    "Chief Security Officer (CSO)",
    "Chief Human Resources Officer (CHRO)",
    "Director of Engineering",
    "Director of Product Management",
    "Director of Operations",
    "Director of Sales",
    "Director of Marketing",
    "Director of Human Resources",
    "Director of Finance",
    "Vice President of Engineering",
    "Vice President of Product",
    "Vice President of Sales",
    "Vice President of Marketing",
    "Vice President of Operations",
    "Vice President of Finance",
    "Vice President of Human Resources",
    "Product Manager",
    "Project Manager",
    "Program Manager",
    "Operations Manager",
    "Engineering Manager",
    "Development Manager",
    "Sales Manager",
    "Marketing Manager",
    "Customer Success Manager",
    "IT Manager",
    "HR Manager",
    "Finance Manager",
    "Compliance Manager",
    "Quality Assurance Manager",
    "Business Development Manager",
    "Account Manager",
    "Client Relationship Manager",
    "Service Delivery Manager",
    "Business Analyst",
    "Data Analyst",
    "Strategy Consultant",
    "Management Consultant",
    "Technical Lead",
    "Team Lead",
    "Solution Architect",
    "Enterprise Architect",
    "Innovation Leader",
    "Transformation Leader",
    "Digital Leader",
    "Community Manager",
    "Growth Hacker",
    "Scrum Master",
    "Agile Coach",
    "Mentor",
    "Advisor",
    "Chief Architect",
    "Head of Research and Development (R&D)",
    "Chief Analytics Officer (CAO)",
    "Chief Digital Officer (CDO)",
];

